### PR TITLE
Fixed bug with renderText

### PR DESCRIPTION
**Pull request by Velover**
-Added instanceBuffer to handle the cases when the instance cannot be disabled in the same frame like billboard gui
-added --!native tag
-fixed weird BillboardGui scale
-changed version of the package

### CODE REVIEW

**Comment by christopher-buss** [comment]
Please don't bump package version in future PRs as I'll bump myself when I create a new release 😄 Also please run StyLua on the Luau file.

In terms of the actual PR though, can you please explain more what you mean by `instance cannot be disabled in the next frame`?

**Comment by Velover** [comment]
I never used StyLua before.

And about the bug. The text didn't work and I looked at why. I found out that if you disable/enable BillboardGui every frame it's not going to rotate towards you (it uses tweening under the hood). So the solution was to delay the disabling of BillboardGui at least until the next frame

**Comment by Velover** [comment]
is this PR going to be merged?

**Comment by christopher-buss** [comment]
Sorry I am quite busy with some things right now. I will get to this at by this weekend.

**Pull request merged**
